### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stweil**
* Fix script statement to create valid HTML / XHTML
* Add hint for .hocr files

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Maybe the examples and `hocrjs-inject.js` should use the `type` attribute, too?

**Comment by kba** [comment]
Did you have a concrete problem with the missing `type` attribute, a specific combination of browser/document? I like the HTML5 convention of omitting `type` from `<script>` and in my experience, modern browsers handle that gracefully also for XHTML/HTML <= 4.01.

Good point about file extensions and mime types.

**Comment by stweil** [comment]
While examining the problems with *.hocr files, I also used the [W3C validator](http://validator.w3.org/) which complains and reports an error. I had no practical problem caused by the missing type attribute.

**Comment by kba** [comment]
I removed the type part (which is not a likely cause for trouble) and expanded on server config. thanks stefan.

**Pull request merged**
